### PR TITLE
Round initial capacity to power-of-two

### LINKED ISSUE #89: Assertion Failed: len.is_power_of_two()
Not particularly sure (yet) what the conditions for trigger are but at this point I've seen this trace twice which is the assert statement within alloc.rs

```
thread 'tokio-runtime-worker' (12) panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/papaya-0.2.3/src/raw/alloc.rs:60:9:
assertion failed: len.is_power_of_two()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Upon re-running the binary I can't replicate but as soon as I can I will follow up here

### PR DESCRIPTION
**Pull request by ibraheemdev**
Resolves https://github.com/ibraheemdev/papaya/issues/89.

### CODE REVIEW

File: src/raw/mod.rs [hunk 1]
```diff
@@ -234,8 +234,10 @@ impl<K, V, S> HashMap<K, V, S> {
             };
         }
 
+        let capacity = probe::entries_for(capacity);
+
         // Initialize the table and mark it as the root.
-        let mut table = Table::alloc(probe::entries_for(capacity));
+        let mut table = Table::alloc(capacity);
```
Comment (deven96) [inline src/raw/mod.rs:240]: Looks to be the same as before?

Comment (ibraheemdev) [reply src/raw/mod.rs:240]: We store the `capacity` a few lines down.
